-- worldcore/infra/schema/041_seed_spells_mvp.sql

BEGIN;

-- Seed: MVP spell + song set currently referenced by worldcore tests/tools.
-- Safe to run repeatedly: uses ON CONFLICT UPSERT.

INSERT INTO public.spells (
    id,
    name,
    description,
    kind,
    class_id,
    min_level,
    school,
    is_song,
    song_school,
    resource_type,
    resource_cost,
    cooldown_ms,
    damage_multiplier,
    flat_bonus,
    heal_amount,
    is_debug,
    is_enabled,
    flags,
    tags,
    is_dev_only,
    grant_min_role
) VALUES
(
    'arcane_bolt',
    'Arcane Bolt',
    'A simple bolt of arcane energy. Reliable, if not subtle.',
    'damage_single_npc',
    'any',
    1,
    'arcane',
    false,
    NULL,
    'mana',
    8,
    2500,
    1.0,
    8,
    NULL,
    false,
    true,
    '{}'::jsonb,
    '{}'::text[],
    false,
    'player'
),
(
    'debug_arcane_bolt',
    'Debug Arcane Bolt',
    'Developer testing spell. Cheap, strong, and intentionally boring.',
    'damage_single_npc',
    'any',
    1,
    'arcane',
    false,
    NULL,
    'mana',
    0,
    0,
    1.0,
    20,
    NULL,
    true,
    true,
    '{}'::jsonb,
    ARRAY['debug','testing']::text[],
    true,
    'dev'
),
(
    'mage_fire_bolt',
    'Fire Bolt',
    'A bolt of flame that scorches a single target.',
    'damage_single_npc',
    'mage',
    1,
    'fire',
    false,
    NULL,
    'mana',
    15,
    2500,
    1.15,
    12,
    NULL,
    false,
    true,
    '{}'::jsonb,
    '{}'::text[],
    false,
    'player'
),
(
    'cleric_minor_heal',
    'Minor Heal',
    'Restore a modest amount of health to yourself.',
    'heal_self',
    'cleric',
    1,
    'holy',
    false,
    NULL,
    'mana',
    18,
    8000,
    NULL,
    NULL,
    40,
    false,
    true,
    '{}'::jsonb,
    '{}'::text[],
    false,
    'player'
),
(
    'virtuoso_song_rising_courage',
    'Song of Rising Courage',
    'A steady melody that bolsters courage and mends small wounds.',
    'heal_self',
    'virtuoso',
    1,
    NULL,
    true,
    'voice',
    'mana',
    12,
    4000,
    NULL,
    NULL,
    20,
    false,
    true,
    '{}'::jsonb,
    '{}'::text[],
    false,
    'player'
),
(
    'virtuoso_hymn_woven_recovery',
    'Hymn of Woven Recovery',
    'A restorative hymn that stitches vitality back into place.',
    'heal_self',
    'virtuoso',
    3,
    NULL,
    true,
    'voice',
    'mana',
    18,
    8000,
    NULL,
    NULL,
    30,
    false,
    true,
    '{}'::jsonb,
    '{}'::text[],
    false,
    'player'
),
(
    'virtuoso_dissonant_battle_chant',
    'Dissonant Battle Chant',
    'A discordant chant that rattles a foe and builds momentum.',
    'damage_single_npc',
    'virtuoso',
    5,
    NULL,
    true,
    'voice',
    'mana',
    15,
    4000,
    1.05,
    8,
    NULL,
    false,
    true,
    '{}'::jsonb,
    '{}'::text[],
    false,
    'player'
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    kind = EXCLUDED.kind,
    class_id = EXCLUDED.class_id,
    min_level = EXCLUDED.min_level,
    school = EXCLUDED.school,
    is_song = EXCLUDED.is_song,
    song_school = EXCLUDED.song_school,
    resource_type = EXCLUDED.resource_type,
    resource_cost = EXCLUDED.resource_cost,
    cooldown_ms = EXCLUDED.cooldown_ms,
    damage_multiplier = EXCLUDED.damage_multiplier,
    flat_bonus = EXCLUDED.flat_bonus,
    heal_amount = EXCLUDED.heal_amount,
    is_debug = EXCLUDED.is_debug,
    is_enabled = EXCLUDED.is_enabled,
    flags = EXCLUDED.flags,
    tags = EXCLUDED.tags,
    is_dev_only = EXCLUDED.is_dev_only,
    grant_min_role = EXCLUDED.grant_min_role,
    updated_at = now();

-- Legacy alias to canonical id mapping
INSERT INTO public.spell_aliases (alias_id, spell_id)
VALUES ('song_virtuoso_battle_chant', 'virtuoso_dissonant_battle_chant')
ON CONFLICT (alias_id) DO UPDATE SET
    spell_id = EXCLUDED.spell_id,
    updated_at = now();

COMMIT;
