-- worldcore/infra/schema/054_seed_common_class_kits_L1_10.sql
-- System 5.x: Minimal L1–10 common spell kit for classes that do not yet have bespoke kits.
--
-- Goal:
-- - Make every selectable class playable to level 10 with a basic kit (nuke + dot + debuff + shield + hot).
-- - Keep identity work for later (per-class bespoke kits can replace these unlocks over time).
--
-- Idempotent: safe to re-run.

BEGIN;

-- ---------------------------------------------------------------------------
-- Spells: common kit (class_id='any')
-- ---------------------------------------------------------------------------
INSERT INTO public.spells (
  id, name, description, kind, class_id, min_level, school,
  is_song, song_school,
  resource_type, resource_cost, cooldown_ms,
  damage_multiplier, flat_bonus, heal_amount,
  status_effect, cleanse,
  is_debug, is_enabled,
  flags, tags,
  is_dev_only, grant_min_role
) VALUES
  (
    'common_strike',
    'Quick Strike',
    'A simple, decisive strike. Not fancy. Effective.',
    'damage_single_npc',
    'any',
    1,
    NULL,
    false, NULL,
    'mana', 6, 1500,
    1.00, 2, NULL,
    NULL::jsonb,
    NULL::jsonb,
    false, true,
    '{"kit":"common_ref_l1_10"}'::jsonb,
    ARRAY['common_kit','ref_l1_10','damage']::text[],
    false, 'player'
  ),
  (
    'common_bleeding_wound',
    'Bleeding Wound',
    'Open a nasty cut that bleeds for a short time.',
    'damage_dot_single_npc',
    'any',
    3,
    NULL,
    false, NULL,
    'mana', 8, 9000,
    1.05, 4, NULL,
    '{"id":"common_bleeding_wound_dot","durationMs":8000,"modifiers":{},"dot":{"tickIntervalMs":2000,"spreadDamageAcrossTicks":true},"tags":["dot","common_kit","ref_l1_10"]}'::jsonb,
    NULL::jsonb,
    false, true,
    '{"kit":"common_ref_l1_10"}'::jsonb,
    ARRAY['common_kit','ref_l1_10','dot']::text[],
    false, 'player'
  ),
  (
    'common_sundered_guard',
    'Sundered Guard',
    'Rattle the target''s defenses, making them take more damage.',
    'debuff_single_npc',
    'any',
    5,
    NULL,
    false, NULL,
    'mana', 9, 12000,
    0.00, 0, NULL,
    '{"id":"common_sundered_guard_debuff","durationMs":12000,"modifiers":{"damageTakenPct":0.08},"tags":["debuff","common_kit","ref_l1_10"]}'::jsonb,
    NULL::jsonb,
    false, true,
    '{"kit":"common_ref_l1_10"}'::jsonb,
    ARRAY['common_kit','ref_l1_10','debuff']::text[],
    false, 'player'
  ),
  (
    'common_barrier',
    'Barrier',
    'A quick protective barrier that absorbs a small amount of damage.',
    'shield_self',
    'any',
    7,
    'arcane',
    false, NULL,
    'mana', 10, 12000,
    0.00, 0, NULL,
    '{"id":"common_barrier_shield","durationMs":12000,"modifiers":{},"absorb":{"amount":15},"tags":["shield","common_kit","ref_l1_10"]}'::jsonb,
    NULL::jsonb,
    false, true,
    '{"kit":"common_ref_l1_10"}'::jsonb,
    ARRAY['common_kit','ref_l1_10','shield']::text[],
    false, 'player'
  ),
  (
    'common_second_wind',
    'Second Wind',
    'Catch your breath and recover steadily for a short time.',
    'heal_hot_self',
    'any',
    9,
    'holy',
    false, NULL,
    'mana', 8, 12000,
    0.00, 0, 16,
    '{"id":"common_second_wind_hot","durationMs":10000,"modifiers":{},"hot":{"tickIntervalMs":2000,"spreadHealingAcrossTicks":true},"tags":["hot","common_kit","ref_l1_10"]}'::jsonb,
    NULL::jsonb,
    false, true,
    '{"kit":"common_ref_l1_10"}'::jsonb,
    ARRAY['common_kit','ref_l1_10','hot']::text[],
    false, 'player'
  )
ON CONFLICT (id)
DO UPDATE SET
  name              = EXCLUDED.name,
  description       = EXCLUDED.description,
  kind              = EXCLUDED.kind,
  class_id          = EXCLUDED.class_id,
  min_level         = EXCLUDED.min_level,
  school            = EXCLUDED.school,
  is_song           = EXCLUDED.is_song,
  song_school       = EXCLUDED.song_school,
  resource_type     = EXCLUDED.resource_type,
  resource_cost     = EXCLUDED.resource_cost,
  cooldown_ms       = EXCLUDED.cooldown_ms,
  damage_multiplier = EXCLUDED.damage_multiplier,
  flat_bonus        = EXCLUDED.flat_bonus,
  heal_amount       = EXCLUDED.heal_amount,
  status_effect     = EXCLUDED.status_effect,
  cleanse           = EXCLUDED.cleanse,
  is_debug          = EXCLUDED.is_debug,
  is_enabled        = EXCLUDED.is_enabled,
  flags             = EXCLUDED.flags,
  tags              = EXCLUDED.tags,
  is_dev_only       = EXCLUDED.is_dev_only,
  grant_min_role    = EXCLUDED.grant_min_role,
  updated_at        = now();

-- ---------------------------------------------------------------------------
-- Spell unlock rules: grant common kit to classes missing bespoke kits
-- ---------------------------------------------------------------------------
INSERT INTO public.spell_unlocks (class_id, spell_id, min_level, auto_grant, is_enabled, notes)
VALUES
  ('illusionist','common_strike', 1, true, true, 'Common kit L1–10: Quick Strike'),
  ('illusionist','common_bleeding_wound', 3, true, true, 'Common kit L1–10: Bleeding Wound'),
  ('illusionist','common_sundered_guard', 5, true, true, 'Common kit L1–10: Sundered Guard'),
  ('illusionist','common_barrier', 7, true, true, 'Common kit L1–10: Barrier'),
  ('illusionist','common_second_wind', 9, true, true, 'Common kit L1–10: Second Wind'),
  ('ascetic','common_strike', 1, true, true, 'Common kit L1–10: Quick Strike'),
  ('ascetic','common_bleeding_wound', 3, true, true, 'Common kit L1–10: Bleeding Wound'),
  ('ascetic','common_sundered_guard', 5, true, true, 'Common kit L1–10: Sundered Guard'),
  ('ascetic','common_barrier', 7, true, true, 'Common kit L1–10: Barrier'),
  ('ascetic','common_second_wind', 9, true, true, 'Common kit L1–10: Second Wind'),
  ('prophet','common_strike', 1, true, true, 'Common kit L1–10: Quick Strike'),
  ('prophet','common_bleeding_wound', 3, true, true, 'Common kit L1–10: Bleeding Wound'),
  ('prophet','common_sundered_guard', 5, true, true, 'Common kit L1–10: Sundered Guard'),
  ('prophet','common_barrier', 7, true, true, 'Common kit L1–10: Barrier'),
  ('prophet','common_second_wind', 9, true, true, 'Common kit L1–10: Second Wind'),
  ('crusader','common_strike', 1, true, true, 'Common kit L1–10: Quick Strike'),
  ('crusader','common_bleeding_wound', 3, true, true, 'Common kit L1–10: Bleeding Wound'),
  ('crusader','common_sundered_guard', 5, true, true, 'Common kit L1–10: Sundered Guard'),
  ('crusader','common_barrier', 7, true, true, 'Common kit L1–10: Barrier'),
  ('crusader','common_second_wind', 9, true, true, 'Common kit L1–10: Second Wind'),
  ('revenant','common_strike', 1, true, true, 'Common kit L1–10: Quick Strike'),
  ('revenant','common_bleeding_wound', 3, true, true, 'Common kit L1–10: Bleeding Wound'),
  ('revenant','common_sundered_guard', 5, true, true, 'Common kit L1–10: Sundered Guard'),
  ('revenant','common_barrier', 7, true, true, 'Common kit L1–10: Barrier'),
  ('revenant','common_second_wind', 9, true, true, 'Common kit L1–10: Second Wind'),
  ('hierophant','common_strike', 1, true, true, 'Common kit L1–10: Quick Strike'),
  ('hierophant','common_bleeding_wound', 3, true, true, 'Common kit L1–10: Bleeding Wound'),
  ('hierophant','common_sundered_guard', 5, true, true, 'Common kit L1–10: Sundered Guard'),
  ('hierophant','common_barrier', 7, true, true, 'Common kit L1–10: Barrier'),
  ('hierophant','common_second_wind', 9, true, true, 'Common kit L1–10: Second Wind'),
  ('defiler','common_strike', 1, true, true, 'Common kit L1–10: Quick Strike'),
  ('defiler','common_bleeding_wound', 3, true, true, 'Common kit L1–10: Bleeding Wound'),
  ('defiler','common_sundered_guard', 5, true, true, 'Common kit L1–10: Sundered Guard'),
  ('defiler','common_barrier', 7, true, true, 'Common kit L1–10: Barrier'),
  ('defiler','common_second_wind', 9, true, true, 'Common kit L1–10: Second Wind'),
  ('conjuror','common_strike', 1, true, true, 'Common kit L1–10: Quick Strike'),
  ('conjuror','common_bleeding_wound', 3, true, true, 'Common kit L1–10: Bleeding Wound'),
  ('conjuror','common_sundered_guard', 5, true, true, 'Common kit L1–10: Sundered Guard'),
  ('conjuror','common_barrier', 7, true, true, 'Common kit L1–10: Barrier'),
  ('conjuror','common_second_wind', 9, true, true, 'Common kit L1–10: Second Wind'),
  ('cutthroat','common_strike', 1, true, true, 'Common kit L1–10: Quick Strike'),
  ('cutthroat','common_bleeding_wound', 3, true, true, 'Common kit L1–10: Bleeding Wound'),
  ('cutthroat','common_sundered_guard', 5, true, true, 'Common kit L1–10: Sundered Guard'),
  ('cutthroat','common_barrier', 7, true, true, 'Common kit L1–10: Barrier'),
  ('cutthroat','common_second_wind', 9, true, true, 'Common kit L1–10: Second Wind'),
  ('ravager','common_strike', 1, true, true, 'Common kit L1–10: Quick Strike'),
  ('ravager','common_bleeding_wound', 3, true, true, 'Common kit L1–10: Bleeding Wound'),
  ('ravager','common_sundered_guard', 5, true, true, 'Common kit L1–10: Sundered Guard'),
  ('ravager','common_barrier', 7, true, true, 'Common kit L1–10: Barrier'),
  ('ravager','common_second_wind', 9, true, true, 'Common kit L1–10: Second Wind'),
  ('primalist','common_strike', 1, true, true, 'Common kit L1–10: Quick Strike'),
  ('primalist','common_bleeding_wound', 3, true, true, 'Common kit L1–10: Bleeding Wound'),
  ('primalist','common_sundered_guard', 5, true, true, 'Common kit L1–10: Sundered Guard'),
  ('primalist','common_barrier', 7, true, true, 'Common kit L1–10: Barrier'),
  ('primalist','common_second_wind', 9, true, true, 'Common kit L1–10: Second Wind'),
  ('outrider','common_strike', 1, true, true, 'Common kit L1–10: Quick Strike'),
  ('outrider','common_bleeding_wound', 3, true, true, 'Common kit L1–10: Bleeding Wound'),
  ('outrider','common_sundered_guard', 5, true, true, 'Common kit L1–10: Sundered Guard'),
  ('outrider','common_barrier', 7, true, true, 'Common kit L1–10: Barrier'),
  ('outrider','common_second_wind', 9, true, true, 'Common kit L1–10: Second Wind'),
  ('hunter','common_strike', 1, true, true, 'Common kit L1–10: Quick Strike'),
  ('hunter','common_bleeding_wound', 3, true, true, 'Common kit L1–10: Bleeding Wound'),
  ('hunter','common_sundered_guard', 5, true, true, 'Common kit L1–10: Sundered Guard'),
  ('hunter','common_barrier', 7, true, true, 'Common kit L1–10: Barrier'),
  ('hunter','common_second_wind', 9, true, true, 'Common kit L1–10: Second Wind'),
  ('runic_knight','common_strike', 1, true, true, 'Common kit L1–10: Quick Strike'),
  ('runic_knight','common_bleeding_wound', 3, true, true, 'Common kit L1–10: Bleeding Wound'),
  ('runic_knight','common_sundered_guard', 5, true, true, 'Common kit L1–10: Sundered Guard'),
  ('runic_knight','common_barrier', 7, true, true, 'Common kit L1–10: Barrier'),
  ('runic_knight','common_second_wind', 9, true, true, 'Common kit L1–10: Second Wind')
ON CONFLICT (class_id, spell_id)
DO UPDATE SET
  min_level  = EXCLUDED.min_level,
  auto_grant = EXCLUDED.auto_grant,
  is_enabled = EXCLUDED.is_enabled,
  notes      = EXCLUDED.notes,
  updated_at = now();

COMMIT;
