-- worldcore/infra/schema/056_seed_crusader_class_kit_L1_10.sql
-- Wave1: Crusader L1–10 starter kit (unique spells) + unlocks.
-- Idempotent: safe to re-run.

BEGIN;

-- 1) Ensure the Crusader kit spells exist in public.spells.
INSERT INTO public.spells (
  id,
  name,
  description,
  kind,
  class_id,
  min_level,
  school,
  is_song,
  song_school,
  resource_type,
  resource_cost,
  cooldown_ms,
  damage_multiplier,
  flat_bonus,
  heal_amount,
  is_debug,
  is_enabled,
  flags,
  tags,
  is_dev_only,
  grant_min_role,
  status_effect,
  cleanse
)
VALUES
  (
    'crusader_oathbound_strike',
    'Oathbound Strike',
    'A disciplined blow that tests your foe and your vow.',
    'damage_single_npc',
    'crusader',
    1,
    'holy',
    false,
    NULL,
    'mana',
    6,
    1500,
    1,
    2,
    NULL,
    false,
    true,
    '{"kit":"ref_l1_10"}'::jsonb,
    '["holy","crusader","reference_kit","ref_l1_10"]'::jsonb,
    false,
    'player',
    NULL,
    NULL
  ),
  (
    'crusader_sanctuary',
    'Sanctuary',
    'A brief ward that turns faith into force.',
    'shield_self',
    'crusader',
    3,
    'holy',
    false,
    NULL,
    'mana',
    8,
    12000,
    NULL,
    NULL,
    NULL,
    false,
    true,
    '{"kit":"ref_l1_10"}'::jsonb,
    '["holy","crusader","shield","reference_kit","ref_l1_10"]'::jsonb,
    false,
    'player',
    '{"id":"shield_crusader_sanctuary","name":"Sanctuary","kind":"shield","durationMs":12000,"shieldAmount":20,"tags":["shield","holy","crusader","reference_kit","ref_l1_10"]}'::jsonb,
    NULL
  ),
  (
    'crusader_purging_vow',
    'Purging Vow',
    'Cast off a single affliction and steady your stance.',
    'cleanse_self',
    'crusader',
    5,
    'holy',
    false,
    NULL,
    'mana',
    10,
    15000,
    NULL,
    NULL,
    NULL,
    false,
    true,
    '{"kit":"ref_l1_10"}'::jsonb,
    '["holy","crusader","cleanse","reference_kit","ref_l1_10"]'::jsonb,
    false,
    'player',
    '{"id":"cleanse_crusader_purging_vow","name":"Purging Vow","kind":"cleanse","maxToRemove":1,"tags":["cleanse","holy","crusader","reference_kit","ref_l1_10"]}'::jsonb,
    '{"tags":["curse","poison","disease","magic"],"maxToRemove":1}'::jsonb
  ),
  (
    'crusader_fervor',
    'Fervor',
    'Steel your will—your next strikes land harder.',
    'buff_self',
    'crusader',
    7,
    'holy',
    false,
    NULL,
    'mana',
    10,
    20000,
    NULL,
    NULL,
    NULL,
    false,
    true,
    '{"kit":"ref_l1_10"}'::jsonb,
    '["holy","crusader","buff","reference_kit","ref_l1_10"]'::jsonb,
    false,
    'player',
    '{"id":"buff_crusader_fervor","name":"Fervor","kind":"buff","durationMs":10000,"maxStacks":1,"stacks":1,"modifiers":{"damageDealtPct":7},"tags":["buff","holy","crusader","reference_kit","ref_l1_10"]}'::jsonb,
    NULL
  ),
  (
    'crusader_verdict',
    'Verdict',
    'A condemnatory mark that makes the foe pay for every mistake.',
    'debuff_single_npc',
    'crusader',
    9,
    'holy',
    false,
    NULL,
    'mana',
    8,
    12000,
    NULL,
    NULL,
    NULL,
    false,
    true,
    '{"kit":"ref_l1_10"}'::jsonb,
    '["holy","crusader","debuff","reference_kit","ref_l1_10"]'::jsonb,
    false,
    'player',
    '{"id":"debuff_crusader_verdict","name":"Verdict","kind":"debuff","durationMs":12000,"maxStacks":1,"stacks":1,"modifiers":{"damageTakenPct":7},"tags":["debuff","holy","crusader","reference_kit","ref_l1_10"]}'::jsonb,
    NULL
  )
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  kind = EXCLUDED.kind,
  class_id = EXCLUDED.class_id,
  min_level = EXCLUDED.min_level,
  school = EXCLUDED.school,
  is_song = EXCLUDED.is_song,
  song_school = EXCLUDED.song_school,
  resource_type = EXCLUDED.resource_type,
  resource_cost = EXCLUDED.resource_cost,
  cooldown_ms = EXCLUDED.cooldown_ms,
  damage_multiplier = EXCLUDED.damage_multiplier,
  flat_bonus = EXCLUDED.flat_bonus,
  heal_amount = EXCLUDED.heal_amount,
  is_debug = EXCLUDED.is_debug,
  is_enabled = EXCLUDED.is_enabled,
  flags = EXCLUDED.flags,
  tags = EXCLUDED.tags,
  is_dev_only = EXCLUDED.is_dev_only,
  grant_min_role = EXCLUDED.grant_min_role,
  status_effect = EXCLUDED.status_effect,
  cleanse = EXCLUDED.cleanse,
  updated_at = now();

-- 2) Unlocks: remove the old templar-mapped kit rows for Crusader (if present), then insert the Crusader kit unlocks.
DELETE FROM public.spell_unlocks
WHERE class_id = 'crusader'
  AND notes = 'wave1 kit: templar map';

INSERT INTO public.spell_unlocks (class_id, spell_id, min_level, auto_grant, is_enabled, notes)
VALUES
  ('crusader', 'crusader_oathbound_strike', 1, true, true, 'wave1 kit: crusader'),
  ('crusader', 'crusader_sanctuary', 3, true, true, 'wave1 kit: crusader'),
  ('crusader', 'crusader_purging_vow', 5, true, true, 'wave1 kit: crusader'),
  ('crusader', 'crusader_fervor', 7, true, true, 'wave1 kit: crusader'),
  ('crusader', 'crusader_verdict', 9, true, true, 'wave1 kit: crusader')
ON CONFLICT (class_id, spell_id) DO UPDATE SET
  min_level = EXCLUDED.min_level,
  auto_grant = EXCLUDED.auto_grant,
  is_enabled = EXCLUDED.is_enabled,
  notes = EXCLUDED.notes,
  updated_at = now();

COMMIT;
